"""
This code was generated by a tool. Don't modify it manually.
http://sqldalmaker.sourceforge.net
"""


class Group:
    """
    @type g_id: java.lang.Object | None
    @type g_name: java.lang.Object | None
    @type tasks_count: java.lang.Object | None
    """

    def __init__(self):
        self.g_id = None  # q(g_id)
        self.g_name = None  # q(g_name)
        self.tasks_count = None  # q(tasks_count)
