"""
This code was generated by a tool. Don't modify it manually.
http://sqldalmaker.sourceforge.net
"""

from dal.group_ex import GroupEx


class GroupsDao:

    def __init__(self, ds):
        self.ds = ds

    def get_groups(self, sql):
        """
        @type sql: str
        @rtype: list[GroupEx]
        """
        _res = []

        def _map_cb(row):
            _obj = GroupEx()
            _obj.g_id = row["g_id"]  # q(g_id) <- q(g_id)
            _obj.g_name = row["g_name"]  # q(g_name) <- q(g_name)
            _obj.g_comments = row["g_comments"]  # q(g_comments) <- q(g_comments)
            _obj.tasks_count = row["tasks_count"]  # q(tasks_count) <- q(tasks_count)
            _res.append(_obj)

        self.ds.query_all_rows(sql, [], _map_cb)
        return _res
