"""
This code was generated by a tool. Don't modify it manually.
http://sqldalmaker.sourceforge.net
"""

from dal.group_ex_model import GroupExModel


class GroupsDao:

    def __init__(self, ds):
        self.ds = ds

    def get_groups(self):
        """
        @rtype: list[GroupExModel]
        """
        sql = """select g.*,  
                (select count(*) from tasks where g_id=g.g_id) as tasks_count 
                from groups g"""
        _res = []

        def _map_cb(row):
            _obj = GroupExModel()
            _obj.g_id = row["g_id"]  # q(g_id) <- q(g_id)
            _obj.g_name = row["g_name"]  # q(g_name) <- q(g_name)
            _obj.tasks_count = row["tasks_count"]  # q(tasks_count) <- q(tasks_count)
            _res.append(_obj)

        self.ds.query_all_rows(sql, [], _map_cb)
        return _res
