"""
This code was generated by a tool. Don't modify it manually.
http://sqldalmaker.sourceforge.net
"""


class Task:
    """
    @type t_id: java.lang.Integer | None
    @type g_id: java.lang.Integer | None
    @type t_priority: java.lang.Integer | None
    @type t_date: str | None
    @type t_subject: str | None
    @type t_comments: str | None
    """

    def __init__(self):
        self.t_id = None  # t(t_id)
        self.g_id = None  # t(g_id)
        self.t_priority = None  # t(t_priority)
        self.t_date = None  # t(t_date)
        self.t_subject = None  # t(t_subject)
        self.t_comments = None  # t(t_comments)
